# Generated by Django 3.1.7 on 2021-07-05 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20210406_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=120, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
