# Generated by Django 3.1.7 on 2021-07-06 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20210705_2113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
