# Generated by Django 3.1.7 on 2021-04-18 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_userprofile_used_coupons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='used_coupons',
        ),
    ]
