# Generated by Django 3.2.7 on 2021-09-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_auto_20210814_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
