# Generated by Django 3.1.7 on 2021-07-12 19:05

from django.db import migrations, models
import profile.validators


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_auto_20210709_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='county',
            field=models.CharField(blank=True, max_length=80, null=True, validators=[profile.validators.validate_county]),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=50, validators=[profile.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[profile.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[profile.validators.validate_postal_code]),
        ),
        migrations.AlterField(
            model_name='order',
            name='street_address1',
            field=models.CharField(max_length=80, validators=[profile.validators.validate_alpha_numeric]),
        ),
        migrations.AlterField(
            model_name='order',
            name='street_address2',
            field=models.CharField(blank=True, max_length=80, null=True, validators=[profile.validators.validate_alpha_numeric]),
        ),
        migrations.AlterField(
            model_name='order',
            name='town_or_city',
            field=models.CharField(max_length=40, validators=[profile.validators.validate_city]),
        ),
    ]
