# Generated by Django 3.1.7 on 2021-09-04 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_auto_20210712_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
    ]
