# Generated by Django 3.1.7 on 2021-08-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.CharField(max_length=420),
        ),
    ]
