# Generated by Django 3.1.7 on 2021-09-02 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0013_auto_20210901_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-published_date']},
        ),
    ]
