# Generated by Django 3.1.7 on 2021-04-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tips',
            name='message',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
