# Generated by Django 3.1.7 on 2021-04-12 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0008_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tips',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='discount_percentage',
            new_name='discount',
        ),
    ]
